// switchyard-contracts.test.mjs — the B1 contracts core of the
// standalone Switchyard package (introduced as increment B1).
//
// Four groups, all hermetic (no network, no DB):
//   1. GOLDEN VECTORS — the digest port must be byte-identical in behavior to
//      inbox-pipeline/src/hash.ts. The fixture digest-golden-vectors.json was
//      GENERATED BY RUNNING the inbox implementation; the port must reproduce
//      every canonical string + digest exactly.
//   2. ContractId grammar accept/reject + parse.
//   3. ArtifactRef / ArtifactEnvelope LOUD validators (digest-sealed).
//   4. Frozen-schema mirror pin-tests — schemas/*
//      must byte-equal the checked-in fixture copies (the mc-harness
//      environment-descriptor pin pattern), and the code patterns/bounds must
//      equal the frozen $defs.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { canonicalJson, digest, rawBodyDigest } from "@scshafe/switchyard/contracts/digest";
import {
  CONTRACT_ID_PATTERN,
  CONTRACT_ID_MAX_LENGTH,
  SHA256_HEX_PATTERN,
  isContractId,
  parseContractId,
  validateContractId,
  assertJsonValue,
  validateArtifactRef,
  validateArtifactEnvelope,
  createArtifactEnvelope,
  artifactRef
} from "@scshafe/switchyard/contracts/artifact";

const fixture = (rel) => new URL(`./fixtures/switchyard/${rel}`, import.meta.url);
const mirror = (rel) => new URL(`../schemas/${rel}`, import.meta.url);

// ── 1. Golden vectors (generated by RUNNING the inbox implementation) ──

const GOLDEN = JSON.parse(readFileSync(fixture("digest-golden-vectors.json"), "utf8"));

test("golden vectors: the port reproduces every inbox canonicalJson + digest byte-for-byte", () => {
  assert.ok(GOLDEN.vectors.length >= 10, "expected ~10+ object vectors");
  for (const vector of GOLDEN.vectors) {
    const value = JSON.parse(vector.inputJson);
    assert.equal(canonicalJson(value), vector.canonical, `canonicalJson mismatch for vector ${vector.name}`);
    assert.equal(digest(value), vector.digest, `digest mismatch for vector ${vector.name}`);
  }
});

test("golden vectors: rawBodyDigest matches the inbox raw-bytes rule (no JSON quoting)", () => {
  assert.ok(GOLDEN.rawBodyVectors.length >= 3, "expected raw-body vectors");
  for (const vector of GOLDEN.rawBodyVectors) {
    assert.equal(rawBodyDigest(vector.input), vector.digest, `rawBodyDigest mismatch for vector ${vector.name}`);
  }
  // The two rules are DISTINCT: a bare string digests as its JSON-quoted form.
  assert.notEqual(digest("hello world"), rawBodyDigest("hello world"));
});

test("golden vectors: key order never changes a digest (permuted twin collapses)", () => {
  const byName = Object.fromEntries(GOLDEN.vectors.map((v) => [v.name, v]));
  assert.equal(byName["nested-objects"].digest, byName["nested-objects-permuted"].digest);
  const a = JSON.parse(byName["nested-objects"].inputJson);
  const b = JSON.parse(byName["nested-objects-permuted"].inputJson);
  assert.equal(digest(a), digest(b));
});

test("foundational canonicalJson/digest retain the published non-plain-object acceptance", () => {
  const epoch = new Date(0);
  assert.equal(canonicalJson(epoch), "{}");
  assert.equal(
    digest(epoch),
    "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
  );
});

// ── 2. ContractId grammar ──

test("contract id grammar: accepts <name>.v<number> and parses name/version", () => {
  const accept = [
    ["email-normalized.v1", "email-normalized", 1],
    ["a.v1", "a", 1],
    ["0x9.v42", "0x9", 42],
    ["a.b-c_d.v2", "a.b-c_d", 2],
    ["usage-receipt.v1", "usage-receipt", 1],
    ["x.v10", "x", 10]
  ];
  for (const [id, name, version] of accept) {
    assert.ok(isContractId(id), `expected accept: ${id}`);
    assert.deepEqual(parseContractId(id), { name, version });
    assert.equal(validateContractId(id), id);
  }
});

test("contract id grammar: rejects LOUDLY with precise messages", () => {
  const reject = [
    "", // empty
    "email", // no version suffix
    "Email.v1", // uppercase name
    "email.V1", // uppercase V
    ".v1", // empty name
    "-a.v1", // bad leading char
    "email.v0", // versions start at 1
    "email.v01", // no leading zero
    "email.v1.5", // trailing junk
    "email.v", // no number
    "sha256:abc.v1", // ':' not in the grammar
    "a".repeat(159) + ".v1" // 162 chars > 160
  ];
  for (const id of reject) {
    assert.ok(!isContractId(id), `expected reject: ${JSON.stringify(id)}`);
    assert.throws(() => parseContractId(id), /contract id/, `expected parse throw: ${JSON.stringify(id)}`);
  }
  assert.throws(() => parseContractId(7), /must be a string \(got number\)/);
  assert.throws(() => validateContractId("Email.v1", "artifact envelope: contractId"), /artifact envelope: contractId/);
});

// ── 3. ArtifactRef + ArtifactEnvelope (digest-sealed, LOUD) ──

test("artifact ref: validates the frozen artifact-ref.v1 shape", () => {
  const good = { contractId: "email-normalized.v1", digest: "a".repeat(64) };
  assert.deepEqual(validateArtifactRef(good), good);
  const withBytes = { ...good, bytes: 123 };
  assert.deepEqual(validateArtifactRef(withBytes), withBytes);
});

test("artifact ref: LOUD failures (non-object, strict keys, sha256: prefix, bad bytes)", () => {
  assert.throws(() => validateArtifactRef(null), /must be a plain object \(got null\)/);
  assert.throws(() => validateArtifactRef([]), /must be a plain object \(got array\)/);
  assert.throws(() => validateArtifactRef({ contractId: "a.v1", digest: "a".repeat(64), extra: 1 }), /unknown key\(s\) "extra"/);
  // The frozen rule: bare hex, NO "sha256:" prefix.
  assert.throws(
    () => validateArtifactRef({ contractId: "a.v1", digest: `sha256:${"a".repeat(64)}` }),
    /NO "sha256:" prefix/
  );
  assert.throws(() => validateArtifactRef({ contractId: "a.v1", digest: "A".repeat(64) }), /bare lowercase sha256 hex/);
  assert.throws(() => validateArtifactRef({ contractId: "a.v1", digest: "a".repeat(63) }), /bare lowercase sha256 hex/);
  assert.throws(() => validateArtifactRef({ contractId: "a.v1", digest: "a".repeat(64), bytes: -1 }), /bytes must be an integer/);
  assert.throws(() => validateArtifactRef({ contractId: "a.v1", digest: "a".repeat(64), bytes: 1.5 }), /bytes must be an integer/);
  assert.throws(() => validateArtifactRef({ contractId: "a.v1", digest: "a".repeat(64), bytes: undefined }), /bytes is present but undefined/);
});

test("artifact envelope: create seals payload digest+bytes; validate round-trips; ref projects", () => {
  const payload = { b: 1, a: { c: [true, null, "x"] } };
  const envelope = createArtifactEnvelope("demo-artifact.v1", payload);
  assert.equal(envelope.digest, digest(payload));
  assert.equal(envelope.bytes, Buffer.byteLength(canonicalJson(payload), "utf8"));
  assert.deepEqual(validateArtifactEnvelope(envelope), envelope);
  assert.deepEqual(artifactRef(envelope), {
    contractId: "demo-artifact.v1",
    digest: envelope.digest,
    bytes: envelope.bytes
  });
  // bytes is optional on a hand-built envelope (artifact-ref.v1: "when known").
  const noBytes = { contractId: envelope.contractId, digest: envelope.digest, payload };
  assert.deepEqual(validateArtifactEnvelope(noBytes), noBytes);
});

test("artifact envelope: sealing uses the SAME canonical rule the golden vectors pin", () => {
  const byName = Object.fromEntries(GOLDEN.vectors.map((v) => [v.name, v]));
  const value = JSON.parse(byName["nested-objects"].inputJson);
  const envelope = createArtifactEnvelope("golden.v1", value);
  assert.equal(envelope.digest, byName["nested-objects"].digest);
  assert.equal(envelope.bytes, Buffer.byteLength(byName["nested-objects"].canonical, "utf8"));
});

test("artifact envelope: LOUD failures (tamper, bytes mismatch, missing payload, strict keys)", () => {
  const envelope = createArtifactEnvelope("demo-artifact.v1", { n: 1 });
  // Tampered payload → digest mismatch names the contract + both digests.
  assert.throws(
    () => validateArtifactEnvelope({ ...envelope, payload: { n: 2 } }),
    /digest mismatch for demo-artifact\.v1 — sealed [a-f0-9]{64} != computed [a-f0-9]{64}/
  );
  // Tampered digest → digest mismatch.
  assert.throws(() => validateArtifactEnvelope({ ...envelope, digest: "b".repeat(64) }), /digest mismatch/);
  // Tampered bytes → bytes mismatch.
  assert.throws(() => validateArtifactEnvelope({ ...envelope, bytes: envelope.bytes + 1 }), /bytes mismatch/);
  // Missing / undefined payload.
  const { payload, ...withoutPayload } = envelope;
  assert.throws(() => validateArtifactEnvelope(withoutPayload), /payload is required/);
  assert.throws(() => validateArtifactEnvelope({ ...envelope, payload: undefined }), /payload is required/);
  // Strict keys.
  assert.throws(() => validateArtifactEnvelope({ ...envelope, sneaky: true }), /unknown key\(s\) "sneaky"/);
  // Bad contract id is labeled.
  assert.throws(() => validateArtifactEnvelope({ ...envelope, contractId: "Nope.v1" }), /contractId: contract id must match/);
});

test("artifact envelope: non-JSON payloads are rejected with the offending path", () => {
  assert.throws(() => createArtifactEnvelope("x.v1", { a: Number.NaN }), /payload\.a: non-finite number NaN/);
  assert.throws(() => createArtifactEnvelope("x.v1", { a: Infinity }), /payload\.a: non-finite number Infinity/);
  assert.throws(() => createArtifactEnvelope("x.v1", { a: { b: [1, undefined] } }), /payload\.a\.b\[1\]/);
  assert.throws(() => createArtifactEnvelope("x.v1", { a: { b: undefined } }), /payload\.a\.b: undefined is not a JSON value/);
  assert.throws(() => createArtifactEnvelope("x.v1", new Date()), /not a JSON value/);
  assert.throws(() => createArtifactEnvelope("x.v1", { a: new Map() }), /payload\.a: .* not a JSON value/);
  assert.throws(() => createArtifactEnvelope("x.v1", () => {}), /function is not a JSON value/);
  // Direct guard export too.
  assert.throws(() => assertJsonValue({ deep: { bad: 0n } }, "p"), /p\.deep\.bad: bigint is not a JSON value/);
  assertJsonValue({ ok: [-0, 1e21, "s", null, true, {}] });
});

// ── 4. Frozen-schema mirror pin-tests ──

const MIRRORED_SCHEMAS = [
  "artifact-ref.v1.schema.json",
  "environment-descriptor.v1.schema.json",
  "usage-receipt.v1.schema.json"
];

for (const name of MIRRORED_SCHEMAS) {
  test(`frozen-schema pin: schemas/${name} byte-equals the checked-in fixture`, () => {
    const mirrored = readFileSync(mirror(name), "utf8");
    const pinned = readFileSync(fixture(name), "utf8");
    assert.equal(mirrored, pinned, `${name}: the package mirror drifted from the frozen fixture copy`);
  });
}

test("frozen-schema pin: code patterns/bounds equal the frozen artifact-ref.v1 $defs", () => {
  const schema = JSON.parse(readFileSync(fixture("artifact-ref.v1.schema.json"), "utf8"));
  assert.equal(CONTRACT_ID_PATTERN.source, schema.$defs.contractId.pattern);
  assert.equal(CONTRACT_ID_MAX_LENGTH, schema.$defs.contractId.maxLength);
  assert.equal(SHA256_HEX_PATTERN.source, schema.$defs.sha256.pattern);
  // The ref shape itself: required + strict.
  assert.deepEqual(schema.required, ["contractId", "digest"]);
  assert.equal(schema.additionalProperties, false);
  assert.equal(schema.properties.bytes.maximum, 9007199254740991);
});

test("frozen-schema pin: environment-descriptor + usage-receipt share the same contractId/sha256 grammar", () => {
  const env = JSON.parse(readFileSync(fixture("environment-descriptor.v1.schema.json"), "utf8"));
  assert.equal(env.$defs.contractId.pattern, CONTRACT_ID_PATTERN.source);
  assert.equal(env.$defs.sha256.pattern, SHA256_HEX_PATTERN.source);
  const usage = JSON.parse(readFileSync(fixture("usage-receipt.v1.schema.json"), "utf8"));
  assert.equal(usage.properties.schemaVersion.const, "usage-receipt.v1");
  assert.ok(isContractId(usage.properties.schemaVersion.const));
  assert.ok(isContractId(env.properties.schemaVersion.const));
});
