// digest.ts — canonical-JSON serialization + SHA-256 digests.
//
// PORTED (behavior byte-identical, export names preserved) from
// `inbox-pipeline/src/hash.ts`; proven by the golden-vector fixture
// `test/fixtures/mission-pipeline/digest-golden-vectors.json`, which was
// GENERATED BY RUNNING the inbox implementation. Any change here that alters a
// produced digest breaks cross-repo content addressing — the golden-vector test
// fails loudly.
//
// STANDALONE: node:crypto + relative imports only (no npm deps).

import { createHash } from "node:crypto";

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      // Cross-repo digest rule: sort keys by the DEFAULT code-unit (UTF-16)
      // comparator, matching JobTrack's `stableJson` and the shared
      // execution-contracts package (CONVENTIONS.md §1, fakes/digest.ts). This
      // replaces the earlier `localeCompare` sort, which diverged from the other
      // repos on any key containing punctuation (`-`/`_`/`.`/`:`), mixed case, or
      // digit/letter adjacency and would silently break cross-repo digest checks.
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
        .map(([key, child]) => [key, canonicalize(child)])
    );
  }
  return value;
}

export function canonicalJson(value: unknown): string {
  return JSON.stringify(canonicalize(value));
}

/**
 * INTERNAL object-canonical digest. `digest(value)` ALWAYS hashes the canonical
 * JSON of `value` — including a bare `string`, which is hashed as its JSON-quoted
 * form (`"…"`), NOT as its raw UTF-8 bytes.
 *
 * A3 (reconciliation H-1): the earlier Phase-1 raw-string exception
 * (`typeof value === "string" ? value : …`) is REVERTED. Inbox never recomputes a
 * raw-body digest across the cross-repo boundary through `digest()`, so the
 * exception bought no cross-repo benefit; meanwhile it silently CHURNED persisted
 * LIVE ingest content digests (`contentDigest = digest(sourceText)` etc.), because
 * every such value moved from `sha256("\"…\"")` to `sha256("…")`. Reverting keeps
 * `digest()` a single, stable object-canonical rule.
 *
 * For any cross-repo raw-string / raw-body digest, use {@link rawBodyDigest} — it
 * is the ONE function that implements the package raw-string rule (bytes, no JSON
 * quoting). Do NOT reach for `digest(someString)` to match a raw-body hash.
 */
export function digest(value: unknown): string {
  return createHash("sha256").update(canonicalJson(value)).digest("hex");
}

/**
 * The ONLY function to use for a cross-repo raw-string / raw-body digest:
 * `sha256(utf8(s))` — the bytes of `s`, with NO JSON quoting or escaping. This
 * matches the shared execution-contracts raw-string rule and JobTrack's raw-body
 * hashing exactly, so a body/string digested here is byte-identical across repos.
 *
 * This is deliberately SEPARATE from {@link digest}: `digest()` is the internal
 * object-canonical rule (a bare string is JSON-quoted); `rawBodyDigest()` is the
 * raw-bytes rule. Keeping them distinct means the raw-string behavior is explicit
 * at every call site and can never silently leak into object digests.
 */
export function rawBodyDigest(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}
