// Repository-specific inputs to the release scripts. The other scripts/*.mjs
// are verbatim copies of scshafe-dev's master (release/scripts/); change this
// file, not them. Generated by scshafe-dev v0.1.0. (write-release-manifest.mjs
// is the one known local difference: see its header.)
export default {
  // Each directory in package.json `files` and what it may contain:
  // TypeScript source, the built lib/, and the published JSON schemas.
  payload: { src: "\\.ts$", lib: "\\.(?:js|d\\.ts)$", schemas: "\\.json$" },
  // Build output `pnpm run clean` removes; never committed (LIB-03): the
  // engine's lib/ and the static SDK's (packages/switchyard-graphpaper).
  clean: ["lib", "packages/switchyard-graphpaper/lib"],
  // Packages the smokes need beside the peers (exact devDependencies).
  smokeExtraPackages: [],
  // Optional-peer phases, e.g. [{ name: "editor", peers: ["@tiptap/core"] }]:
  // the base smokes prove these peers are absent, then each phase adds its
  // peers and runs test/smoke/<name>/. switchyard has no peers.
  phases: [],
  // false: the TypeScript smoke also checks the peers' declarations.
  typeSmokeSkipLibCheck: false,
  // DOM as well: peers' declarations name AbortSignal and friends (the
  // switchyard-postgres and graphpaper smokes check them the same way).
  typeSmokeLib: ["ES2022", "DOM"]
};
